#!/usr/bin/env sh

#Run this script will install the dotfiles.

#Check whether the ~/.dotfiles directory exists.
if [ -d ~/.dotfiles ]; then
    echo "~/.dotfiles directory exists. Exit."
    exit 1
fi

#Clone the dotfiles from github.
#Use this childish ASCII art to make it rock a little bit.
printf "\n"
echo "#######################################"
echo "#  Now clone dotfiles into .dotfiles  #"
echo "#######################################"
printf "\n"

git clone https://github.com/Winiex/dotfiles.git ~/.dotfiles
cd ~/.dotfiles

echo "Success"

#Install vim configurations.
printf "\n"
echo "#######################################"
echo "#  Now install vim configurations     #"
echo "#######################################"
printf "\n"

git submodule init
git submodule update

if [ -d ~/.vim ]; then
    echo "Found existing .vim directory in your HOME directory."
    echo "Move it to ~/.vim_backup."
    mv ~/.vim ~/.vim_backup
fi

if [ -f ~/.vimrc ]; then
    echo "Found existing .vimrc file in your HOME directory."
    echo "Move it to ~/.vimrc_backup."
    mv ~/.vimrc ~/.vimrc_backup
fi

ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/vim/ ~/.vim

echo "Success"

#Install bash configurations.
printf "\n"
echo "#######################################"
echo "#  Now install bash configurations    #"
echo "#######################################"
printf "\n"

if [ -f ~/.bash_profile ]; then
    echo "Found existing .bash_profile file in your HOME directory."
    echo "Move it to ~/.bash_profile_backup."
    mv ~/.bash_profile ~/.bash_profile_backup
fi

if [ -f ~/.bashrc ]; then
    echo "Found existing .bashrc file in your HOME directory."
    echo "Move it to ~/.bashrc_backup."
    mv ~/.bashrc ~/.bashrc_backup
fi

ln -s ~/.dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/.dotfiles/bash/bashrc ~/.bashrc
ln -s ~/.dotfiles/bash/bash-it ~/.bash_it

echo "Success"

#Install tmux configurations.
printf "\n"
echo "#######################################"
echo "#  Now install tmux configurations    #"
echo "#######################################"
printf "\n"

if [ -f ~/.tmux.conf ]; then
    echo "Found existing .tmux.conf file in your HOME directory."
    echo "Move it to ~/.tmux.conf_backup"
    mv ~/.tmux.conf ~/.tmux.conf_backup
fi

ln -s ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf

echo "Success"

#Install custom tools.
printf "\n"
echo "#######################################"
echo "#  Now install bash configurations    #"
echo "#######################################"
printf "\n"

if [ -d ~/bin ]; then
    echo "Found existing bin directory in your HOME directory."
    echo "Move it to ~/bin_backup."
    mv ~/bin ~/bin_backup
fi

ln -s ~/.dotfiles/bin ~/bin
tmux source-file ~/.tmux.conf

echo "Success"

printf "\n"
echo "#######################################"
echo "#  Dotfiles install success. Enjoy.:) #"
echo "#######################################"
printf "\n"
