#!/usr/bin/env sh

#Run this script will install the dotfiles.

#Clone the dotfiles from github.
#Use this childish ASCII art to make it rock a little bit.
printf "\n"
echo "#######################################"
echo "#  Now clone dotfiles into .dotfiles  #"
echo "#######################################"
printf "\n"

git clone https://github.com/Winiex/dotfiles.git ~/.dotfiles
cd ~/.dotfiles

#Install vim configurations.
printf "\n"
echo "#######################################"
echo "#  Now install vim configurations     #"
echo "#######################################\n"
printf "\n"

git submodule init
git submodule update

ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/vim/ ~/.vim

#Install bash configurations.
printf "\n"
echo "#######################################"
echo "#  Now install bash configurations    #"
echo "#######################################\n"
printf "\n"

if [ -f ~/.bash_profile ]; then
    echo "Found existing .bash_profile in your HOME directory."
    echo "Move it to ~/.bash_profile_backup."
    mv ~/.bash_profile ~/.bash_profile_backup
fi

if [ -f ~/.bashrc ]; then
    echo "Found existing .bashrc in your HOME directory."
    echo "Move it to ~/.bashrc_backup."
    mv ~/.bashrc ~/.bashrc_backup
fi

ln -s ~/.dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/.dotfiles/bash/bashrc ~/.bashrc
ln -s ~/.dotfiles/bash/bash-it ~/.bash_it

printf "\n"
echo "#######################################"
echo "#  Now configure bash_it              #"
echo "#######################################\n"
printf "\n"

~/.bash_it/install.sh
