#!/usr/bin/env bash

distro=`uname -a`

# Take linux distro into consideration, because in arch linux, python's default version is python 3000
if [[ "$distro" == *Arch* ]]
then
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2.7
fi

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='rjorgenson'

# Set my editor and git editor
export EDITOR="/usr/bin/vim"
export GIT_EDITOR='/usr/bin/vim'

# Load Bash It
source $BASH_IT/bash_it.sh

# Load virtualenvwrapper.sh
if [ -f /usr/bin/virtualenvwrapper.sh ]; then
    source /usr/bin/virtualenvwrapper.sh
fi

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
